apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  selector:
    app: flask-app
    component: greeting